apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "oauth2-proxy-cwd-nginx-name" .}}
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log  /var/log/nginx/access.log main;
      upstream backend-secure {
        server {{.Values.cwd.nginx.config.host }}:443;
      }

      server {
        listen 80;
        server_name localhost;

        proxy_redirect          https://{{.Values.cwd.nginx.config.host }} http://$http_host;
        proxy_set_header        Host            {{.Values.cwd.nginx.config.host }};
        proxy_set_header        Origin          https://{{.Values.cwd.nginx.config.host }};
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
                proxy_pass  https://backend-secure;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "oauth2-proxy-cwd-internal-nginx-name" .}}
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'http_host:$http_host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log  /var/log/nginx/access.log main;
      upstream backend-secure {
        server {{.Values.cwd.internal.nginx.config.host }}:443;
      }

      server {
        listen 80;
        server_name localhost;

        proxy_redirect          https://{{.Values.cwd.internal.nginx.config.host }} http://$http_host;
        proxy_set_header        Host            {{.Values.cwd.internal.nginx.config.host }};
        proxy_set_header        Origin          https://{{.Values.cwd.internal.nginx.config.host }};
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            proxy_pass  https://backend-secure;
        }
      }
    }