apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-client-secret
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "portal.config.clientSecret is required" .Values.portal.config.clientSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-internal-client-secret
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "cwd.config.internal.clientSecret is required" .Values.cwd.config.internal.clientSecret | b64enc }}
