apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: logging-common-base
    app.kubernetes.io/name: fluentbit
  name: logging-common-base-fluentbit
  namespace: system
secrets:
- name: logging-common-base-fluentbit-token-mz8zz
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: logging-common-base
    app.kubernetes.io/name: fluentd
  name: logging-common-base-fluentd
  namespace: system
secrets:
- name: logging-common-base-fluentd-token-lzbcm
