apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/managed-by: logging-common-base
    app.kubernetes.io/name: fluentbit
  name: logging-common-base-fluentbit
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: logging-common-base
      app.kubernetes.io/name: fluentbit
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: logging-common-base
        app.kubernetes.io/name: fluentbit
    spec:
      containers:
      - image: iad.ocir.io/dataservicedev1/fluent/fluent-bit:1.3.2
        imagePullPolicy: IfNotPresent
        name: fluent-bit
        ports:
        - containerPort: 2020
          name: monitor
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 300M
          requests:
            cpu: 300m
            memory: 200M
        volumeMounts:
        - mountPath: /var/lib/docker/containers
          name: varlibcontainers
          readOnly: true
        - mountPath: /tail-db
          name: positiondb
        - mountPath: /buffers
          name: buffers
        - mountPath: /var/log/
          name: varlogs
          readOnly: true
        - mountPath: /u01/data/docker/containers
          name: extravolumemount0
          readOnly: true
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: config
          subPath: fluent-bit.conf
        - mountPath: /fluent-bit/tls/
          name: fluent-bit-tls
      volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibcontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlogs
      - hostPath:
          path: /u01/data/docker/containers
          type: ""
        name: extravolumemount0
      - name: config
        secret:
          defaultMode: 420
          items:
          - key: fluent-bit.conf
            path: fluent-bit.conf
          secretName: logging-common-base-fluentbit
      - name: fluent-bit-tls
        secret:
          defaultMode: 420
          secretName: logging-common-base-fluentbit-tls
      - emptyDir: {}
        name: positiondb
      - emptyDir: {}
        name: buffers
