apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/managed-by: logging-common-base
    app.kubernetes.io/name: fluentd
  name: logging-common-base-fluentd
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: logging-common-base
      app.kubernetes.io/name: fluentd
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: logging-common-base
        app.kubernetes.io/name: fluentd
    spec:
      containers:
      - args:
        - fluentd
        - -o
        - /fluentd/log/out
        - --log-rotate-age
        - "10"
        - --log-rotate-size
        - "10485760"
        env:
        - name: BUFFER_PATH
          value: /buffers
        image: iad.ocir.io/dataservicedev1/cre/banzaicloud/fluentd:v1.7.4
        imagePullPolicy: IfNotPresent
        name: fluentd
        ports:
        - containerPort: 24240
          name: fluent-input
          protocol: TCP
        - containerPort: 24231
          name: monitor
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 400M
          requests:
            cpu: 500m
            memory: 100M
        volumeMounts:
        - mountPath: /fluentd/etc/
          name: config
        - mountPath: /fluentd/app-config/
          name: app-config
        - mountPath: /fluentd/secret
          name: output-secret
        - mountPath: /buffers
          name: logging-common-base-fluentd-buffer
        - mountPath: /fluentd/tls/
          name: fluentd-tls
      - args:
        - -volume-dir=/fluentd/etc
        - -volume-dir=/fluentd/app-config/
        - -webhook-url=http://127.0.0.1:24444/api/config.reload
        image: iad.ocir.io/dataservicedev1/jimmidyson/configmap-reload:v0.2.2
        imagePullPolicy: IfNotPresent
        name: config-reloader
        volumeMounts:
        - mountPath: /fluentd/etc
          name: config
        - mountPath: /fluentd/app-config/
          name: app-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 101
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: logging-common-base-fluentd
      - name: app-config
        secret:
          defaultMode: 420
          secretName: logging-common-base-fluentd-app
      - name: output-secret
        secret:
          defaultMode: 420
          secretName: logging-common-base-fluentd-output
      - name: logging-common-base-fluentd-buffer
        persistentVolumeClaim:
          claimName: fluentd-buffer
      - name: fluentd-tls
        secret:
          defaultMode: 420
          secretName: logging-common-base-fluentd-tls
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app.kubernetes.io/managed-by: logging-common-base
        app.kubernetes.io/name: fluentd
      name: logging-common-base-fluentd-buffer
      namespace: system
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
