affinity: {}
apiSideEffectValue: NoneOnDryRun
certificate:
  ca:
    crt: null
  generate: true
  server:
    tls:
      crt: null
      key: null
configMapMutation: false
configmapFailurePolicy: Ignore
debug: false
env:
  VAULT_ENV_IMAGE: banzaicloud/vault-env:0.8.0
  VAULT_IMAGE: vault:1.3.1
image:
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  repository: banzaicloud/vault-secrets-webhook
  tag: 0.8.0
labels: {}
metrics:
  enabled: false
  port: 8443
  serviceMonitor:
    enabled: false
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
namespaceSelector:
  matchExpressions:
  - key: name
    operator: NotIn
    values:
    - kube-system
nodeSelector: {}
objectSelector: {}
podAnnotations: {}
podDisruptionBudget:
  enabled: true
  minAvailable: 1
podsFailurePolicy: Ignore
priorityClassName: ""
rbac:
  enabled: true
  psp:
    enabled: false
replicaCount: 2
resources: {}
secretsFailurePolicy: Ignore
service:
  externalPort: 443
  internalPort: 8443
  name: vault-secrets-webhook
  type: ClusterIP
tolerations: []
volumeMounts: []
volumes: []
