{{/*apiVersion: cert-manager.io/v1alpha2*/}}
{{/*kind: ClusterIssuer*/}}
{{/*metadata:*/}}
{{/*  name: selfsigning-issuer*/}}
{{/*  labels:*/}}
{{/*    {{- include "edge.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  selfSigned: {}*/}}
