{{- if .Values.telepresence.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge.name" . }}-telepresence
  labels:
    {{- include "edge.labels" . | nindent 4 }}
spec:
  replicas: 1  # only one replica
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "edge.name" . }}-telepresence
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "edge.name" . }}-telepresence
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      containers:
      - name: myservice
        image: "{{ .Values.telepresence.image.repository }}:{{ .Values.telepresence.image.tag }}"
{{- end }}
