apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.vault.name }}-oci
  labels:
    {{- include "topsecret.labels" . | nindent 4 }}
data:
  config: {{ include "topsecret.oci-config" . | b64enc }}
{{- if  .Values.vault.oci.user.apiKeyFilePath }}
  oci_api_key.pem: {{ .Files.Get (.Values.oci.user.apiKeyFilePath) | b64enc }}
{{- else if .Values.vault.oci.user.apiKey }}
  oci_api_key.pem: {{ .Values.vault.oci.user.apiKey | b64enc }}
{{- else if .Values.vault.oci.user.apiKeyBase64 }}
  oci_api_key.pem: {{ .Values.vault.oci.user.apiKeyBase64 }}
{{- else }}
  {{ required "vault.oci.user.apiKeyFilePath or vault.oci.user.apiKey (or global) value is required, if it so please your highness." false }}
{{- end }}
