apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-pv

spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/datas
     