apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  labels:
    name: pv-pod

spec:
  containers:
    - name: pv-pod
      image: nginx
      volumeMounts:
        - name: test-pd
          mountPath: /oracle-pd
      ports:
        - containerPorts: 80
  volumes:
    - name: test-pd
      persistentVolumeClaim:
        claimName: kube-pvc