apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod

spec:
  containers:
    - name: tomcat-container
      image: vishymails/tomcatimage:1.0
      volumeMounts:
        - name: cache-volume
          mountPath: /oracle-volume

  volumes:
    - name: cache-volume
      emptyDir: {}