apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig

data:
  db_host_name: "oraclehost"
  db_url: "sql:///localhost:3306"

  service-details: |
    components=admission-service, pathology-service
    rating=5

  css-properties:
    colour = red
    background = yellow
    text-color = black
    