apiVersion: v1
kind: Pod
metadata:
  name: myconfigpod
  labels:
    name: myconfigpod

spec:
  containers:
    - name: myconfigpod
      image: redis
      volumeMounts:
        - name: foo
          mountPath: "/etc/config"
          readOnly: true


  volumes:
    - name: foo
      configMap:
        name: myconfig