apiVersion: v1
kind: pod
metadata:
  name: liveness
  labels:
    test: liveness

spec:
  containers:
    - name: liveness
      image: vishymails/tomcatimage:1.0
      args:
        - /bin/sh
        - -c
        - echo OK > /tmp/health; sleep 10; rm -rf /tmp/health; sleep 120
      livenessProbe:
        exec:
          command:
            - cat
            - /etc/health
        initialDelaySeconds: 15
        timeoutSeconds: 1
        

        