apiVersion: v1
kind: Service
metadata:
  name: {{ template "cwd-ldap-internal.name" . }}
  labels:
{{ include "cwd-ldap-internal.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: serevice
  selector:
{{ include "cwd-ldap-internal.labels" . | indent 4 }}