# Source: edge/charts/ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
  labels:
    helm.sh/chart: ingress-nginx-4.3.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: edge
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: edge-ingress-nginx-controller
  namespace: system
spec:
  type: LoadBalancer
  loadBalancerIP: 144.25.82.172
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: edge
    app.kubernetes.io/component: controller
