apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"edge","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.4.0","helm.sh/chart":"ingress-nginx-4.3.0"},"name":"edge-ingress-nginx-controller","namespace":"system"},"spec":{"loadBalancerIP":"144.25.82.172","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"},{"name":"https","port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"edge","app.kubernetes.io/name":"ingress-nginx"},"type":"LoadBalancer"}}
    meta.helm.sh/release-name: edge
    meta.helm.sh/release-namespace: system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: edge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.4.0
    helm.sh/chart: ingress-nginx-4.3.0
  name: edge-ingress-nginx-controller
  namespace: system
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.141.50
  clusterIPs:
  - 10.96.141.50
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 144.25.82.172
  ports:
  - appProtocol: http
    name: http
    nodePort: 32605
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30670
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: edge
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 138.3.86.181
