apiVersion: v1
kind: Service
metadata:
  name: {{ include "cwd-coordinator-internal.fullname" . }}
  labels:
    {{- include "cwd-coordinator-internal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "cwd-coordinator-internal.selectorLabels" . | nindent 4 }}
