apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwd-coordinator.fullname" . }}-cwddb-secret
  labels:
    {{- include "cwd-coordinator.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "cwdDb.password is required" .Values.cwdDb.password | b64enc }}
stringData:
  username: {{ required "cwdDb.username is required" .Values.cwdDb.username }}
