
helmDefaults:
  wait: false
  timeout: 600
  force: false
  recreatePods: false

repositories:
  - name: cwd-helm
    url: https://artifactory.oci.oraclecorp.com:443/cwd-dev-helm-virtual

environments:
  {{ .Environment.Name }}: {}

releases:
  - name: monitoring
    namespace: system
    chart: .
    values:
      - ../../environments/{{ .Environment.Name }}/monitoring.yaml
