---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cwd-ldap-properties-name" . }}
  labels:
  {{- include "cwd-ldap.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: {{ .Values.container.port | quote}}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:oracle:thin:@%s?TNS_ADMIN=/workspace/CWD/wallet"  .Values.cwd.ldap.db.dbName | quote  }}
  CWD_LDAP_LDAPSERVICE_PROVIDERURL: {{ .Values.cwd.ldap.LdapService.providerUrl | quote }}
  CWD_LDAP_LDAPSERVICE_SEARCHBASE: {{ .Values.cwd.ldap.LdapService.searchBase | quote }}
  CWD_LDAP_LDAPSERVICE_ATTRIBUTENAME: {{ .Values.cwd.ldap.LdapService.attributeName | quote }}
  CWD_LDAP_LDAPSERVICE_SEARCHFILTERKEY: {{ .Values.cwd.ldap.LdapService.searchFilterKey | quote }}
  CWD_LDAP_LDAPSERVICE_SEARCHRESULTPATTERN: {{ .Values.cwd.ldap.LdapService.searchResultPattern | quote }}
  CWD_LDAP_LDAPCONSUMER_PERIODMS: {{ .Values.cwd.ldap.LdapConsumer.periodMs | quote}}
  CWD_LDAP_LDAPCONSUMER_GROUPS: {{ .Values.cwd.ldap.LdapConsumer.groups | quote }}
  CWD_LDAP_OCEANSERVICE_CLIENTID: {{ .Values.cwd.ldap.OceanService.clientId | quote }}
  CWD_LDAP_OCEANSERVICE_TENANCYID: {{ .Values.cwd.ldap.OceanService.tenancyId | quote }}
  CWD_LDAP_OCEANSERVICE_HEADERCLIENTID: {{ .Values.cwd.ldap.OceanService.headerClientId | quote }}
  CWD_LDAP_OCEANSERVICE_HEADERSECRET: {{ .Values.cwd.ldap.OceanService.headerSecret | quote }}
  CWD_LDAP_OCEANSERVICE_HEADERTENANCYID: {{ .Values.cwd.ldap.OceanService.headerTenancyId | quote }}
  CWD_LDAP_OCEANSERVICE_ORGID: {{ .Values.cwd.ldap.OceanService.orgId | quote }}
  CWD_LDAP_OCEANSERVICE_URLCREATEINCIDENT: {{ .Values.cwd.ldap.OceanService.urlCreateIncident | quote }}
  CWD_LDAP_OCEANSERVICE_URLINCIDENTATTACHMENT: {{ .Values.cwd.ldap.OceanService.urlIncidentAttachment | quote }}
  CWD_LDAP_OCEANSERVICE_URLCREATEINCIDENTTYPE: {{ .Values.cwd.ldap.OceanService.urlCreateIncidentType | quote }}
  CWD_LDAP_OCEANSERVICE_INCIDENTTAGS: {{ .Values.cwd.ldap.OceanService.incidentTags | quote }}
  CWD_LDAP_OCEANSERVICE_INCIDENTTAGENV: {{ .Values.cwd.ldap.OceanService.incidentTagEnv | quote }}
  CWD_LDAP_OCEANSERVICE_INCIDENTTAGSVC: {{ .Values.cwd.ldap.OceanService.incidentTagSvc | quote }}
  CWD_LDAP_OCEANSERVICE_URLCREATEINCIDENTSTATUS: {{ .Values.cwd.ldap.OceanService.urlCreateIncidentStatus | quote }}
  CWD_LDAP_OCEANSERVICE_URLCREATEINCIDENTRESPONSEHEADER: {{ .Values.cwd.ldap.OceanService.urlCreateIncidentResponseHeader | quote }}
  CWD_LDAP_OCEANCONSUMER_PERIODMS: {{ .Values.cwd.ldap.OceanConsumer.periodMs | quote }}
