apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwd-ldap.fullname" . }}-cwddb-secret
  labels:
    {{- include "cwd-ldap.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "cwd.ldap.db.password is required" .Values.cwd.ldap.db.password | b64enc }}
stringData:
  username: {{ required "cwd.ldap.db.username is required" .Values.cwd.ldap.db.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-wallet-secret-name" . }}
  labels:
    {{- include "cwd-ldap.labels" . | nindent 4 }}
type: Opaque
data:
  wallet.zip: {{ .Values.cwd.ldap.db.walletZipContentsBase64 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwd-ldap.fullname" . }}-incident-secret
  labels:
    {{- include "cwd-ldap.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "cwd.ldap.OceanService.secret is required" .Values.cwd.ldap.OceanService.secret | b64enc }}

