affinity: {}
crdAnnotations: {}
etcd-operator:
  enabled: false
  etcdOperator:
    commandArgs:
      cluster-wide: true
      create-crd: false
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: banzaicloud/vault-operator
  tag: 0.9.0
labels: {}
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
nameOverride: ""
priorityClassName: ""
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  externalPort: 80
  internalPort: 8080
  type: ClusterIP
syncPeriod: 1m
terminationGracePeriodSeconds: 10
watchNamespace: ""
