{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "tpaas-server-api-name" . }}
  labels:
{{ include "tpaas-server-api.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations.path | indent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- if .Values.ingress.ssl.api.enabled }}
    {{- range .Values.ingress.ssl.api.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- else }}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.api.hostname }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "tpaas-server-api-name" . }}
                port:
                  number: {{ .Values.components.api.service.port }}
{{- end }}
---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "tpaas-server-gitbook-name" . }}
  labels:
{{ include "tpaas-server-gitbook.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations.path | indent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.ui.hostname }}
      http:
        paths:
          - path: /tpaas-docs/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "tpaas-server-gitbook-name" . }}
                port:
                  number: {{ .Values.components.gitbook.service.port }}
  {{- end }}
---
  {{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "tpaas-server-gitbook-name" . }}-docs
  labels:
{{ include "tpaas-server-gitbook.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations.gitbook.path | indent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.ui.hostname }}
      http:
        paths:
          - path: /(tpaas-documents|tpaas-assets|gitbook)/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "tpaas-server-gitbook-name" . }}
                port:
                  number: {{ .Values.components.gitbook.service.port }}
  {{- end }}
