apiVersion: v1
kind: Secret
metadata:
  name: wallet
  labels:
    {{- include "tpaas-server.labels" . | nindent 4 }}
data:
  wallet.zip: {{ .Values.infra.database.walletZipContentsBase64 }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oci-private-keys-secret-name" . }}
  labels:
    {{- include "tpaas-server.labels" . | nindent 4 }}
type: Opaque
data:
  OCI_PRIVATE_KEY: {{ required ".Values.oci.credentials.privatekey is required" .Values.oci.credentials.privatekey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tpaas-server.fullname" . }}-passwords
  labels:
    {{- include "tpaas-server.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PWD: {{ required "infra.database.password is required" .Values.infra.database.password | b64enc }}
  MAIL_PWD: {{ required "components.api.mail.password is required" .Values.components.api.mail.password | b64enc }}
  REPORT_SECRET: {{ required "components.reportServer.secret is required" .Values.components.reportServer.secret | b64enc }}
  REDIS_PWD: {{ required "infra.redis.password is required" .Values.infra.redis.password | b64enc }}