{{- if .Values.ingress.ssl.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.ingress.ssl.name }}
  labels:
{{ include "tpaas-server.labels" . | indent 4 }}
data:
  tls.crt: {{ .Values.ingress.ssl.tls_crt | b64enc }}
  tls.key: {{ .Values.ingress.ssl.tls_key | b64enc }}
{{- end }}
---
{{- if .Values.ingress.ssl.api.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.ingress.ssl.name }}-api
  labels:
{{ include "tpaas-server.labels" . | indent 4 }}
data:
  tls.crt: {{ .Values.ingress.ssl.api.tls_crt | b64enc }}
  tls.key: {{ .Values.ingress.ssl.api.tls_key | b64enc }}
{{- end }}
