helmDefaults:
  wait: false
  timeout: 600
  force: false
  recreatePods: false

repositories: []

environments:
  {{ .Environment.Name }}: {}

releases:
 - name: cwd-ldap-internal
   namespace: cwd-apps
   chart: .
   values:
   - ../../environments/{{ .Environment.Name }}/cwd-ldap-internal.yaml